### ISSUE TITLE
AutoBrightness commits

### ISSUE THREAD

**Issue by davidtrpcevski** [Alexey71/android_device_xiaomi_mido_oreo#1]
Not really an issue but a request to add this commit back with its relevant changes

https://github.com/Alexey71/android_device_xiaomi_mido_Project_is_closed/commit/5280134a600d4464ad65da9fb9ec8b6cc4166736

**Comment by Alexey71** [comment]
Has already

https://github.com/Alexey71/android_device_xiaomi_mido_oreo/commit/4ac0ecd0888d7ec1c8f12952b5904d741957478a#diff-380e537acdaedd487ca1adb49d020f7e
